name: TimeTable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build with donet
      run: dotnet test --no-build --verbosity normal
  deploy:
    needs: build
    name: Deploy app
    runs-on: windows-latest
    
    steps:
    - name: Deploy to azure web app
    uses: azure/appservice-actions/webapp@master
    with:
      app-name: mynewestwebapplication
      publish-profile ${{ secrets.azureWebAppPublishProfile }}
